### ISSUE TITLE
Panic when decoding images

### ISSUE THREAD

**Issue by sxyazi** [etemesi254/zune-image#184] opened 2024-04-05 09:37 UTC
Hi, after upgrading to image v0.25.1 (`image` v0.25 switched to `zune-jpeg`), I occasionally encounter panic when decoding certain JPEGs.

I found the code location that causes it based on the stack trace:

https://github.com/etemesi254/zune-image/blob/db7a5ee61be52cda2cd56e47dfedd2e42ca91bd5/crates/zune-jpeg/src/mcu.rs#L209-L211

And it was fixed in https://github.com/etemesi254/zune-image/commit/1f943d81b1eb189535abfd2afac8f017c57164f3, but the latest `zune-jpeg` 0.4.11 does not include this fix. Is it possible to release a new patch version for it?

**Comment by uklotzde** [comment] 2024-04-05 12:56
This panic happens in `zune-jpeg` with `DecoderOptions::default().set_strict_mode(false)`.

```
thread 'main' panicked at .cargo/registry/src/index.crates.io-6f17d22bba15001f/zune-jpeg-0.4.11/src/mcu.rs:209:9:
assertion `left == right` failed
  left: 5040000
 right: 5880000
```

With the default options `Error: "Premature end of buffer"` is returned as expected.

Unfortunately, I cannot share my test image.

**Comment by etemesi254** [comment] 2024-04-05 19:04
working on it, sorry for the crash, it just happens that it was reported when i was overhauling the api and couldn't hot fix it

**Comment by uklotzde** [comment] 2024-04-06 09:00
How about adding a regression test for this case? To ensure that this does not happen again in the future.

**Comment by etemesi254** [comment] 2024-04-07 16:52
Thank you @uklotzde  for the suggestion, I thought I had added a testcase but was for another problem.

Added in https://github.com/etemesi254/zune-image/commit/212837674b3e4ab93b50cba596cfc18faa4b0f23

Also fixed this in `0.5.0-rc0` which is now up in crates.io So closing this.

Thank you for reporting

**Closed by etemesi254** 2024-04-07 16:52 UTC

**Comment by zphixon** [comment] 2024-05-05 02:33
Hi, is it possible to release a 0.4.12 version that removes this assert?

**Comment by uklotzde** [comment] 2024-05-05 08:40
> Hi, is it possible to release a 0.4.12 version that removes this assert? I ran into it on this seemingly valid image

This would be a low effort quick fix to resolve the issue temporarily. Clients will handle the subsequent decoding error gracefully.

Many downstream dependencies that have upgraded to `image` v0.25.x are affected. Crashing applications for no valid reason is very inconvenient.

**Comment by uklotzde** [comment] 2024-05-05 08:42
...especially now since image v0.25 is actively promoted: https://www.reddit.com/r/rust/comments/1cj94va/image_v025_performance_improvements/

**Comment by rohitmittapalli** [comment] 2024-07-09 19:52
Bump on releasing a 0.4.12 issue to resolve this! Happy to help here and update the image crate as needed.
