### ISSUE TITLE
Slightly different decoding of a handful of JPEG images

### ISSUE THREAD

**Issue by Shnatsel** [etemesi254/zune-image#40] opened 2022-12-31 20:36 UTC
On this image the red area is a few pixels higher compared to decoding with GIMP.

![cs_CZ](https://user-images.githubusercontent.com/291257/210155195-bacb7798-ab4d-4ac9-b6e1-370a0ace80e7.jpg)

I'm genuinely not sure what the correct decoding is, and it's not a huge visual difference, but I thought I'd report it regardless.

Here's another one:

![Art_Jiang_che](https://user-images.githubusercontent.com/291257/210155213-94fffadb-5d1f-4894-994e-c1e53b526a9b.jpg)

It seems to always affect the reddish parts, as far as I can tell.

**Comment by etemesi254** [comment] 2022-12-31 21:49
Will investigate

**Comment by etemesi254** [comment] 2022-12-31 21:59
THe issue will probably stem from us having different color conversion techniques, I use an integer one while libjpeg-turbo uses a fixed floating point one(higher precision than mine), there are plans to change it though to closely libjpeg-turbo

**Comment by etemesi254** [comment] 2023-01-02 14:41
For the flag,this was a bug,on investigation, more visible in this image, caused by padding bytes values being used for upscaling.(if you zoom in on gimp, you can see the red dots appearing on the left) for the master branch.

![red](https://user-images.githubusercontent.com/24320659/210245639-c44a1524-ca1d-4c3d-8b19-8f17eaa9e6c4.jpeg)


The bug is fixed on the dev branch.

For colorspace precision, I'm not looking for 100% compatibility with libjpeg/libjpeg-turbo, so it's not in my end goals.

**Closed by etemesi254** 2023-01-02 14:41 UTC
