### ISSUE TITLE
PNG: some images are decoded incorrectly

### ISSUE THREAD

**Issue by Shnatsel** [etemesi254/zune-image#97] opened 2023-03-08 19:44 UTC
A sampling of 50 images with different failure modes - some are fully transparent, others garbled:

[zune_png_divergences_99d956e64.tar.gz](https://github.com/etemesi254/zune-image/files/10924478/zune_png_divergences_99d956e64.tar.gz)

Tested on commit 99d956e643179a8e293b079396cd578cd9c6a51b (latest as of this writing)

**Comment by etemesi254** [comment] 2023-03-12 12:40
Should be fixed by 88431bc41ab1ce46fafc94841b6763f8fb00767f

And tests added to prevent regression at https://github.com/etemesi254/zune-image/commit/00cddc3769f3e5247a753cb00638f41b23e679da (for how the tests work, see https://github.com/etemesi254/zune-image/blob/dev/docs/AddingATest.md

Could you run to confirm if it's okay

**Comment by Shnatsel** [comment] 2023-03-12 15:11
Some images in this archive still diverge:

```
0.545455 tffff_.png
0.545455 tffff.png
0.45475 tbbn0g04_.png
0.45475 tbbn0g04.png
0.411206 4f14b7aab3a41855378c5517342598b9_.png
0.411206 4f14b7aab3a41855378c5517342598b9.png
0.35588 42ec8668adb5dbc6581393f463976510_.png
0.35588 42ec8668adb5dbc6581393f463976510.png
0.209813 tbbn1g04_.png
0.209813 tbbn1g04.png
```

**Comment by etemesi254** [comment] 2023-03-12 19:07
Could you confirm now? Was not handling transparency chunks lesser than 8 bytes per pixels which led to the divergence

**Comment by Shnatsel** [comment] 2023-03-12 19:13
Three images still diverge:

```
21709.8 (0.33127) 42ec8668adb5dbc6581393f463976510.png
21709.8 (0.33127) 42ec8668adb5dbc6581393f463976510_.png
26948.4 (0.411206) 4f14b7aab3a41855378c5517342598b9.png
26948.4 (0.411206) 4f14b7aab3a41855378c5517342598b9_.png
35746.4 (0.545455) tffff.png
35746.4 (0.545455) tffff_.png
```

(six files due to duplicates; my duplicate finder missed these, I've filed a bug)

**Comment by etemesi254** [comment] 2023-03-12 20:08
> 42ec8668adb5dbc6581393f463976510_.png

The divergences occur because of spec compliance.

tRNS chunks appears after IDAT, png ignores it, ffmpeg errors out, I just allow it.

Since png ignores it, it treats the image as grayscale, I treat it as grayscale with alpha.

Otherwise it should be a hard error

> tffff.png

tRNS values are bigger than depth, I mask the values at https://github.com/etemesi254/zune-image/blob/9d88d5b3c4d9b42136b5c6f5701e09777ad0bc1f/zune-png/src/decoder.rs#L562-L564 to try to continue decoding.

> 4f14b7aab3a41855378c5517342598b9.png

Decoders don't read the tRNS chunk, they treat it as an error as it contains more values than the palette chunk.

Imagemagick treats it as RGB, png treats it as RGBA but palette are set to 255 instead of zero.

Should I treat each one of this as an error?

**Comment by Shnatsel** [comment] 2023-03-12 20:59
I just wanted to bring these files to your attention. I don't really care what happens to these, I trust you know what you're doing with them.

I'm going to close this as resolved and do another run on the entire corpus.

**Closed** 2023-03-12 21:05 UTC

**Comment by etemesi254** [comment] 2023-03-12 21:19
The last one was more of a question(Hope I didn't come of as rude).

I.e on strictness level of the decoder, you deal with more decoders than I do, so you know a thing or two more on how they treat divergences, and hence wanted your opinion on them

**Comment by Shnatsel** [comment] 2023-03-12 21:27
It didn't feel rude, no. But I don't have an in-depth understanding of the formats, so I can't meaningfully comment on this either. By and large as long as you believe the diverging behavior to be correct, I'm fine with that.

**Comment by Shnatsel** [comment] 2023-03-12 22:01
That's it! There are no more divergences on my corpus.

**Comment by Lokathor** [comment] 2023-03-25 18:43
just a follow up comment: @etemesi254 you wondered how strict a decoder should be: the png spec says that it's basically up to each decoder if they want to be strict about things like chunk ordering. You're entirely fine if the decoder chooses to process a tRNS chunk after IDAT.

https://www.w3.org/TR/png/#13Decoders.Errors
