### ISSUE TITLE
Code doesn't compile with only png and jpeg enabled

### ISSUE THREAD

**Issue by emoon** [etemesi254/zune-image#175] opened 2024-03-23 12:18 UTC
Hi,

If I use the following

```toml
zune-image = { version = "0.4", default-features = false, features = ["jpeg", "png"] }
```
The code doesn't compile with the following error
```Rust
  --> /home/emoon/.cargo/registry/src/index.crates.io-6f17d22bba15001f/zune-image-0.4.15/src/codecs/png.rs:13:5
   |
13 | use exif::experimental::Writer;
   |     ^^^^ use of undeclared crate or module `exif`

error[E0282]: type annotations needed for `std::io::Cursor<Vec<_>>`
   --> /home/emoon/.cargo/registry/src/index.crates.io-6f17d22bba15001f/zune-image-0.4.15/src/codecs/png.rs:176:13
    |
176 |         let mut buf = std::io::Cursor::new(vec![]);
    |             ^^^^^^^
    |
help: consider giving `buf` an explicit type, where the placeholders `_` are specified
    |
176 |         let mut buf: std::io::Cursor<Vec<_>> = std::io::Cursor::new(vec![]);
    |                    +++++++++++++++++++++++++
 ```
If I enable the `default-features` it works.

**Comment by etemesi254** [comment] 2024-03-23 13:32
duplicate of

https://github.com/etemesi254/zune-image/issues/164


fixed, and tried adding the ci check in https://github.com/etemesi254/zune-image/blob/dev/.github/workflows/image_features.yml, but I think it's not yet running

I couldn't push a release because I have been overhauling the read and write api to support arbitrary streams for a `0.5` and I can spend my time on as much sadly.

**Comment by emoon** [comment] 2024-03-23 13:34
Thanks!

**Closed** 2024-03-23 13:42 UTC
